import Head from "next/head";
import React from "react";
import CopyrightSection from "../../components/CopyrightSection";
import Footer from "../../components/Footer";
import NavBar from "../../components/NavBar";
import TopBar from "../../components/TopBar";
import SurahViewSideBar from "../../components/SurahViewSideBar";

const SurahViewPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-inter bg-color1 flex flex-col min-h-screen">
        <TopBar />
        <NavBar />
        <div className="flex-grow">
          <SurahViewSideBar />
        </div>
        {/* <Footer />
        <CopyrightSection /> */}
      </main>
    </>
  );
};

export default SurahViewPage;
