import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import TopBar from "@/components/TopBar";
import ApplyForm from "@/components/course/ApplyForm";
import PrivateGuideSection from "@/components/course/PrivateGuideSection";
import PrivateHero from "@/components/course/PrivateHero";
import TutorsSection from "@/components/course/TutorsSection";
import Head from "next/head";
import Image from "next/image";
import { useState, useEffect } from "react";

const PrivateCoursePage = () => {
  const [tutors, setTutors] = useState([]);
  const [selectedTutor, setSelectedTutor] = useState("");

  useEffect(() => {
    fetch("/api/v1/teacher/list", {
      method: "GET",
      redirect: "follow",
    })
      .then((response) => response.json())
      .then((result) => setTutors(result))
      .catch((error) => console.log("error", error));
  }, []);

  return (
    <>
      <Head>
        <title>Studerakoranen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-inter bg-color1 overflow-x-hidden">
        <TopBar />
        <NavBar />
        <PrivateHero />
        <div className="relative h-0.5 w-[30rem] mx-auto">
          <Image fill src={"/assets/borderh.png"} alt="" />
        </div>
        <PrivateGuideSection />
        <TutorsSection tutors={tutors} setSelectedTutor={setSelectedTutor} />
        <ApplyForm tutors={tutors} selectedTutor={selectedTutor} />
        <Footer />
      </main>
    </>
  );
};

export default PrivateCoursePage;
