import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import TopBar from "@/components/TopBar";
import PrivateGuideSection from "@/components/course/PrivateGuideSection";
import PrivateHero from "@/components/course/PrivateHero";
import Head from "next/head";
import Image from "next/image";

const PrivateCoursePage = () => {
  return (
    <>
      <Head>
        <title>Studerakoranen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-inter bg-color1 overflow-x-hidden">
        <TopBar />
        <NavBar />
        <PrivateHero />
        <div className="relative h-0.5 w-[30rem] mx-auto">
          <Image fill src={"/assets/borderh.png"} alt="" />
        </div>
        <PrivateGuideSection />
        <Footer />
      </main>
    </>
  );
};

export default PrivateCoursePage;
