import * as React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import NavBar from '~/components/NavBar'
import TopBar from '~/components/TopBar'
import PrivateHero from '~/components/course/PrivateHero'
import TutorsSection from '~/components/course/TutorsSection'
import ApplyForm from '~/components/course/ApplyForm'
const PrivateCoursePage = () => {
  const [tutors, setTutors] = React.useState([])
  const [selectedTutor, setSelectedTutor] = React.useState('')
  console.log('tutors', tutors)

  React.useEffect(() => {
    fetch('/api/v1/teacher/list', {
      method: 'GET',
      redirect: 'follow',
    })
      .then((response) => response.json())
      .then((result) => setTutors(result))
      .catch((error) => console.log('error', error))
  }, [])

  return (
    <React.Fragment>
      <Head>
        <title>Studerakoranen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-inter bg-color1 overflow-x-hidden">
        <TopBar />
        <NavBar />
        <PrivateHero />
        <div className="hidden md:block relative h-1 w-[80vw] mx-auto mb-10">
          <Image fill src={'/assets/borderh.png'} alt="" />
        </div>
        <TutorsSection tutors={tutors} setSelectedTutor={setSelectedTutor} />
        <ApplyForm tutors={tutors} selectedTutor={selectedTutor} />
      </main>
    </React.Fragment>
  )
}

export default PrivateCoursePage
